version: '3'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app-php-apache
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - my-network

  mysql:
    image: mysql:8.0
    container_name: my-app-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - ./App/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
